const ShopActionTypes = {
  STORE_POSTINGS: 'STORE_POSTINGS',
  STORE_POSTINGS_SUCCESS: 'STORE_POSTINGS_SUCCESS',
  STORE_POSTINGS_FAILURE: 'STORE_POSTINGS_FAILURE',
  CHANGE_CREATED_AT: 'CHANGE_CREATED_AT',
};

export default ShopActionTypes;
