const PosttingsActionTypes = {
  STORE_POSTINGS: 'STORE_POSTINGS',
  FETCH_POSTINGS_START: 'FETCH_POSTINGS_START',
  FETCH_POSTINGS_SUCCESS: 'FETCH_POSTINGS_SUCCESS',
  FETCH__POSTINGS_FAILURE: 'FETCH__POSTINGS_FAILURE',
  CHANGE_CREATED_AT: 'CHANGE_CREATED_AT',
  STORE_FILTER: 'STORE_FILTER',
};

export default PosttingsActionTypes;
